//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.SINCO.WEB.wsListaPrecio {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsListaPrecio.IwsListaPrecio")]
    public interface IwsListaPrecio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsListaPrecio/wsObtenerNombreWS", ReplyAction="http://tempuri.org/IwsListaPrecio/wsObtenerNombreWSResponse")]
        string wsObtenerNombreWS();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsListaPrecio/wsObtenerNombreWS", ReplyAction="http://tempuri.org/IwsListaPrecio/wsObtenerNombreWSResponse")]
        System.Threading.Tasks.Task<string> wsObtenerNombreWSAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsListaPrecio/Obtener", ReplyAction="http://tempuri.org/IwsListaPrecio/ObtenerResponse")]
        string Obtener(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsListaPrecio/Obtener", ReplyAction="http://tempuri.org/IwsListaPrecio/ObtenerResponse")]
        System.Threading.Tasks.Task<string> ObtenerAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsListaPrecio/Listar", ReplyAction="http://tempuri.org/IwsListaPrecio/ListarResponse")]
        string Listar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsListaPrecio/Listar", ReplyAction="http://tempuri.org/IwsListaPrecio/ListarResponse")]
        System.Threading.Tasks.Task<string> ListarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsListaPrecio/Buscar", ReplyAction="http://tempuri.org/IwsListaPrecio/BuscarResponse")]
        string Buscar(int MarcaId, int ModeloId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsListaPrecio/Buscar", ReplyAction="http://tempuri.org/IwsListaPrecio/BuscarResponse")]
        System.Threading.Tasks.Task<string> BuscarAsync(int MarcaId, int ModeloId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IwsListaPrecioChannel : Pacifico.SINCO.WEB.wsListaPrecio.IwsListaPrecio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IwsListaPrecioClient : System.ServiceModel.ClientBase<Pacifico.SINCO.WEB.wsListaPrecio.IwsListaPrecio>, Pacifico.SINCO.WEB.wsListaPrecio.IwsListaPrecio {
        
        public IwsListaPrecioClient() {
        }
        
        public IwsListaPrecioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IwsListaPrecioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IwsListaPrecioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IwsListaPrecioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string wsObtenerNombreWS() {
            return base.Channel.wsObtenerNombreWS();
        }
        
        public System.Threading.Tasks.Task<string> wsObtenerNombreWSAsync() {
            return base.Channel.wsObtenerNombreWSAsync();
        }
        
        public string Obtener(int Id) {
            return base.Channel.Obtener(Id);
        }
        
        public System.Threading.Tasks.Task<string> ObtenerAsync(int Id) {
            return base.Channel.ObtenerAsync(Id);
        }
        
        public string Listar() {
            return base.Channel.Listar();
        }
        
        public System.Threading.Tasks.Task<string> ListarAsync() {
            return base.Channel.ListarAsync();
        }
        
        public string Buscar(int MarcaId, int ModeloId) {
            return base.Channel.Buscar(MarcaId, ModeloId);
        }
        
        public System.Threading.Tasks.Task<string> BuscarAsync(int MarcaId, int ModeloId) {
            return base.Channel.BuscarAsync(MarcaId, ModeloId);
        }
    }
}
