//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.SINCO.WEB.wsListaPrecio {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsListaPrecio.IListaPrecioWS")]
    public interface IListaPrecioWS {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListaPrecioWS/wsObtenerNombreWS", ReplyAction="http://tempuri.org/IListaPrecioWS/wsObtenerNombreWSResponse")]
        string wsObtenerNombreWS();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListaPrecioWS/wsObtenerNombreWS", ReplyAction="http://tempuri.org/IListaPrecioWS/wsObtenerNombreWSResponse")]
        System.Threading.Tasks.Task<string> wsObtenerNombreWSAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListaPrecioWS/Obtener", ReplyAction="http://tempuri.org/IListaPrecioWS/ObtenerResponse")]
        string Obtener(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListaPrecioWS/Obtener", ReplyAction="http://tempuri.org/IListaPrecioWS/ObtenerResponse")]
        System.Threading.Tasks.Task<string> ObtenerAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListaPrecioWS/Listar", ReplyAction="http://tempuri.org/IListaPrecioWS/ListarResponse")]
        string Listar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListaPrecioWS/Listar", ReplyAction="http://tempuri.org/IListaPrecioWS/ListarResponse")]
        System.Threading.Tasks.Task<string> ListarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListaPrecioWS/Buscar", ReplyAction="http://tempuri.org/IListaPrecioWS/BuscarResponse")]
        string Buscar(int marcaId, int modeloId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListaPrecioWS/Buscar", ReplyAction="http://tempuri.org/IListaPrecioWS/BuscarResponse")]
        System.Threading.Tasks.Task<string> BuscarAsync(int marcaId, int modeloId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IListaPrecioWSChannel : Pacifico.SINCO.WEB.wsListaPrecio.IListaPrecioWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ListaPrecioWSClient : System.ServiceModel.ClientBase<Pacifico.SINCO.WEB.wsListaPrecio.IListaPrecioWS>, Pacifico.SINCO.WEB.wsListaPrecio.IListaPrecioWS {
        
        public ListaPrecioWSClient() {
        }
        
        public ListaPrecioWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ListaPrecioWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ListaPrecioWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ListaPrecioWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string wsObtenerNombreWS() {
            return base.Channel.wsObtenerNombreWS();
        }
        
        public System.Threading.Tasks.Task<string> wsObtenerNombreWSAsync() {
            return base.Channel.wsObtenerNombreWSAsync();
        }
        
        public string Obtener(int id) {
            return base.Channel.Obtener(id);
        }
        
        public System.Threading.Tasks.Task<string> ObtenerAsync(int id) {
            return base.Channel.ObtenerAsync(id);
        }
        
        public string Listar() {
            return base.Channel.Listar();
        }
        
        public System.Threading.Tasks.Task<string> ListarAsync() {
            return base.Channel.ListarAsync();
        }
        
        public string Buscar(int marcaId, int modeloId) {
            return base.Channel.Buscar(marcaId, modeloId);
        }
        
        public System.Threading.Tasks.Task<string> BuscarAsync(int marcaId, int modeloId) {
            return base.Channel.BuscarAsync(marcaId, modeloId);
        }
    }
}
