//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.SINCO.WEB.wsPresupuesto {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsPresupuesto.IwsPresupuesto")]
    public interface IwsPresupuesto {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsPresupuesto/wsObtenerNombreWS", ReplyAction="http://tempuri.org/IwsPresupuesto/wsObtenerNombreWSResponse")]
        string wsObtenerNombreWS();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsPresupuesto/wsObtenerNombreWS", ReplyAction="http://tempuri.org/IwsPresupuesto/wsObtenerNombreWSResponse")]
        System.Threading.Tasks.Task<string> wsObtenerNombreWSAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsPresupuesto/ObtenerPresupuesto", ReplyAction="http://tempuri.org/IwsPresupuesto/ObtenerPresupuestoResponse")]
        string ObtenerPresupuesto(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsPresupuesto/ObtenerPresupuesto", ReplyAction="http://tempuri.org/IwsPresupuesto/ObtenerPresupuestoResponse")]
        System.Threading.Tasks.Task<string> ObtenerPresupuestoAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsPresupuesto/ListarPresupuesto", ReplyAction="http://tempuri.org/IwsPresupuesto/ListarPresupuestoResponse")]
        string ListarPresupuesto();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsPresupuesto/ListarPresupuesto", ReplyAction="http://tempuri.org/IwsPresupuesto/ListarPresupuestoResponse")]
        System.Threading.Tasks.Task<string> ListarPresupuestoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsPresupuesto/BuscarPresupuesto", ReplyAction="http://tempuri.org/IwsPresupuesto/BuscarPresupuestoResponse")]
        string BuscarPresupuesto(string NumPresupuesto, string NumInforme, string NumPoliza, string FechaPresupuesto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsPresupuesto/BuscarPresupuesto", ReplyAction="http://tempuri.org/IwsPresupuesto/BuscarPresupuestoResponse")]
        System.Threading.Tasks.Task<string> BuscarPresupuestoAsync(string NumPresupuesto, string NumInforme, string NumPoliza, string FechaPresupuesto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsPresupuesto/AgregarPresupuesto", ReplyAction="http://tempuri.org/IwsPresupuesto/AgregarPresupuestoResponse")]
        string AgregarPresupuesto(Pacifico.SINCO.EN.MSPresupuesto Presupuesto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsPresupuesto/AgregarPresupuesto", ReplyAction="http://tempuri.org/IwsPresupuesto/AgregarPresupuestoResponse")]
        System.Threading.Tasks.Task<string> AgregarPresupuestoAsync(Pacifico.SINCO.EN.MSPresupuesto Presupuesto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsPresupuesto/ModificarPresupuesto", ReplyAction="http://tempuri.org/IwsPresupuesto/ModificarPresupuestoResponse")]
        string ModificarPresupuesto(Pacifico.SINCO.EN.MSPresupuesto Presupuesto, Pacifico.SINCO.EN.MSDetallePresupuesto[] DestallePresupuesto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsPresupuesto/ModificarPresupuesto", ReplyAction="http://tempuri.org/IwsPresupuesto/ModificarPresupuestoResponse")]
        System.Threading.Tasks.Task<string> ModificarPresupuestoAsync(Pacifico.SINCO.EN.MSPresupuesto Presupuesto, Pacifico.SINCO.EN.MSDetallePresupuesto[] DestallePresupuesto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IwsPresupuestoChannel : Pacifico.SINCO.WEB.wsPresupuesto.IwsPresupuesto, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IwsPresupuestoClient : System.ServiceModel.ClientBase<Pacifico.SINCO.WEB.wsPresupuesto.IwsPresupuesto>, Pacifico.SINCO.WEB.wsPresupuesto.IwsPresupuesto {
        
        public IwsPresupuestoClient() {
        }
        
        public IwsPresupuestoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IwsPresupuestoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IwsPresupuestoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IwsPresupuestoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string wsObtenerNombreWS() {
            return base.Channel.wsObtenerNombreWS();
        }
        
        public System.Threading.Tasks.Task<string> wsObtenerNombreWSAsync() {
            return base.Channel.wsObtenerNombreWSAsync();
        }
        
        public string ObtenerPresupuesto(int Id) {
            return base.Channel.ObtenerPresupuesto(Id);
        }
        
        public System.Threading.Tasks.Task<string> ObtenerPresupuestoAsync(int Id) {
            return base.Channel.ObtenerPresupuestoAsync(Id);
        }
        
        public string ListarPresupuesto() {
            return base.Channel.ListarPresupuesto();
        }
        
        public System.Threading.Tasks.Task<string> ListarPresupuestoAsync() {
            return base.Channel.ListarPresupuestoAsync();
        }
        
        public string BuscarPresupuesto(string NumPresupuesto, string NumInforme, string NumPoliza, string FechaPresupuesto) {
            return base.Channel.BuscarPresupuesto(NumPresupuesto, NumInforme, NumPoliza, FechaPresupuesto);
        }
        
        public System.Threading.Tasks.Task<string> BuscarPresupuestoAsync(string NumPresupuesto, string NumInforme, string NumPoliza, string FechaPresupuesto) {
            return base.Channel.BuscarPresupuestoAsync(NumPresupuesto, NumInforme, NumPoliza, FechaPresupuesto);
        }
        
        public string AgregarPresupuesto(Pacifico.SINCO.EN.MSPresupuesto Presupuesto) {
            return base.Channel.AgregarPresupuesto(Presupuesto);
        }
        
        public System.Threading.Tasks.Task<string> AgregarPresupuestoAsync(Pacifico.SINCO.EN.MSPresupuesto Presupuesto) {
            return base.Channel.AgregarPresupuestoAsync(Presupuesto);
        }
        
        public string ModificarPresupuesto(Pacifico.SINCO.EN.MSPresupuesto Presupuesto, Pacifico.SINCO.EN.MSDetallePresupuesto[] DestallePresupuesto) {
            return base.Channel.ModificarPresupuesto(Presupuesto, DestallePresupuesto);
        }
        
        public System.Threading.Tasks.Task<string> ModificarPresupuestoAsync(Pacifico.SINCO.EN.MSPresupuesto Presupuesto, Pacifico.SINCO.EN.MSDetallePresupuesto[] DestallePresupuesto) {
            return base.Channel.ModificarPresupuestoAsync(Presupuesto, DestallePresupuesto);
        }
    }
}
