//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.SINCO.WEB.wsInformeAccidente {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsInformeAccidente.IwsInformeAccidente")]
    public interface IwsInformeAccidente {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsInformeAccidente/wsObtenerNombreWS", ReplyAction="http://tempuri.org/IwsInformeAccidente/wsObtenerNombreWSResponse")]
        string wsObtenerNombreWS();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsInformeAccidente/wsObtenerNombreWS", ReplyAction="http://tempuri.org/IwsInformeAccidente/wsObtenerNombreWSResponse")]
        System.Threading.Tasks.Task<string> wsObtenerNombreWSAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsInformeAccidente/Obtener", ReplyAction="http://tempuri.org/IwsInformeAccidente/ObtenerResponse")]
        string Obtener(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsInformeAccidente/Obtener", ReplyAction="http://tempuri.org/IwsInformeAccidente/ObtenerResponse")]
        System.Threading.Tasks.Task<string> ObtenerAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsInformeAccidente/Listar", ReplyAction="http://tempuri.org/IwsInformeAccidente/ListarResponse")]
        string Listar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsInformeAccidente/Listar", ReplyAction="http://tempuri.org/IwsInformeAccidente/ListarResponse")]
        System.Threading.Tasks.Task<string> ListarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsInformeAccidente/Buscar", ReplyAction="http://tempuri.org/IwsInformeAccidente/BuscarResponse")]
        string Buscar(string NumPoliza, string TipoSiniestro, string FechaSiniestro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsInformeAccidente/Buscar", ReplyAction="http://tempuri.org/IwsInformeAccidente/BuscarResponse")]
        System.Threading.Tasks.Task<string> BuscarAsync(string NumPoliza, string TipoSiniestro, string FechaSiniestro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsInformeAccidente/Agregar", ReplyAction="http://tempuri.org/IwsInformeAccidente/AgregarResponse")]
        string Agregar(Pacifico.SINCO.EN.MSInformeAccidente model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsInformeAccidente/Agregar", ReplyAction="http://tempuri.org/IwsInformeAccidente/AgregarResponse")]
        System.Threading.Tasks.Task<string> AgregarAsync(Pacifico.SINCO.EN.MSInformeAccidente model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsInformeAccidente/Modificar", ReplyAction="http://tempuri.org/IwsInformeAccidente/ModificarResponse")]
        string Modificar(Pacifico.SINCO.EN.MSInformeAccidente model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsInformeAccidente/Modificar", ReplyAction="http://tempuri.org/IwsInformeAccidente/ModificarResponse")]
        System.Threading.Tasks.Task<string> ModificarAsync(Pacifico.SINCO.EN.MSInformeAccidente model);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IwsInformeAccidenteChannel : Pacifico.SINCO.WEB.wsInformeAccidente.IwsInformeAccidente, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IwsInformeAccidenteClient : System.ServiceModel.ClientBase<Pacifico.SINCO.WEB.wsInformeAccidente.IwsInformeAccidente>, Pacifico.SINCO.WEB.wsInformeAccidente.IwsInformeAccidente {
        
        public IwsInformeAccidenteClient() {
        }
        
        public IwsInformeAccidenteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IwsInformeAccidenteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IwsInformeAccidenteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IwsInformeAccidenteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string wsObtenerNombreWS() {
            return base.Channel.wsObtenerNombreWS();
        }
        
        public System.Threading.Tasks.Task<string> wsObtenerNombreWSAsync() {
            return base.Channel.wsObtenerNombreWSAsync();
        }
        
        public string Obtener(int Id) {
            return base.Channel.Obtener(Id);
        }
        
        public System.Threading.Tasks.Task<string> ObtenerAsync(int Id) {
            return base.Channel.ObtenerAsync(Id);
        }
        
        public string Listar() {
            return base.Channel.Listar();
        }
        
        public System.Threading.Tasks.Task<string> ListarAsync() {
            return base.Channel.ListarAsync();
        }
        
        public string Buscar(string NumPoliza, string TipoSiniestro, string FechaSiniestro) {
            return base.Channel.Buscar(NumPoliza, TipoSiniestro, FechaSiniestro);
        }
        
        public System.Threading.Tasks.Task<string> BuscarAsync(string NumPoliza, string TipoSiniestro, string FechaSiniestro) {
            return base.Channel.BuscarAsync(NumPoliza, TipoSiniestro, FechaSiniestro);
        }
        
        public string Agregar(Pacifico.SINCO.EN.MSInformeAccidente model) {
            return base.Channel.Agregar(model);
        }
        
        public System.Threading.Tasks.Task<string> AgregarAsync(Pacifico.SINCO.EN.MSInformeAccidente model) {
            return base.Channel.AgregarAsync(model);
        }
        
        public string Modificar(Pacifico.SINCO.EN.MSInformeAccidente model) {
            return base.Channel.Modificar(model);
        }
        
        public System.Threading.Tasks.Task<string> ModificarAsync(Pacifico.SINCO.EN.MSInformeAccidente model) {
            return base.Channel.ModificarAsync(model);
        }
    }
}
