//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.SINCO.WEB.wsInformeAccidente {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TecnicoEN", Namespace="http://schemas.datacontract.org/2004/07/Pacifico.SINCO.EN")]
    [System.SerializableAttribute()]
    public partial class TecnicoEN : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoMaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoPaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DisponibleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumTecnicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Pacifico.SINCO.WEB.wsInformeAccidente.TallerEN TallerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TallerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TecnicoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoMaterno {
            get {
                return this.ApellidoMaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoMaternoField, value) != true)) {
                    this.ApellidoMaternoField = value;
                    this.RaisePropertyChanged("ApellidoMaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoPaterno {
            get {
                return this.ApellidoPaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoPaternoField, value) != true)) {
                    this.ApellidoPaternoField = value;
                    this.RaisePropertyChanged("ApellidoPaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Disponible {
            get {
                return this.DisponibleField;
            }
            set {
                if ((this.DisponibleField.Equals(value) != true)) {
                    this.DisponibleField = value;
                    this.RaisePropertyChanged("Disponible");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumTecnico {
            get {
                return this.NumTecnicoField;
            }
            set {
                if ((object.ReferenceEquals(this.NumTecnicoField, value) != true)) {
                    this.NumTecnicoField = value;
                    this.RaisePropertyChanged("NumTecnico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Pacifico.SINCO.WEB.wsInformeAccidente.TallerEN Taller {
            get {
                return this.TallerField;
            }
            set {
                if ((object.ReferenceEquals(this.TallerField, value) != true)) {
                    this.TallerField = value;
                    this.RaisePropertyChanged("Taller");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TallerId {
            get {
                return this.TallerIdField;
            }
            set {
                if ((this.TallerIdField.Equals(value) != true)) {
                    this.TallerIdField = value;
                    this.RaisePropertyChanged("TallerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TecnicoId {
            get {
                return this.TecnicoIdField;
            }
            set {
                if ((this.TecnicoIdField.Equals(value) != true)) {
                    this.TecnicoIdField = value;
                    this.RaisePropertyChanged("TecnicoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TallerEN", Namespace="http://schemas.datacontract.org/2004/07/Pacifico.SINCO.EN")]
    [System.SerializableAttribute()]
    public partial class TallerEN : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TallerIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Distrito {
            get {
                return this.DistritoField;
            }
            set {
                if ((object.ReferenceEquals(this.DistritoField, value) != true)) {
                    this.DistritoField = value;
                    this.RaisePropertyChanged("Distrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TallerId {
            get {
                return this.TallerIdField;
            }
            set {
                if ((this.TallerIdField.Equals(value) != true)) {
                    this.TallerIdField = value;
                    this.RaisePropertyChanged("TallerId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsInformeAccidente.IInformeAccidenteWS")]
    public interface IInformeAccidenteWS {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInformeAccidenteWS/ObtenerNombreWS", ReplyAction="http://tempuri.org/IInformeAccidenteWS/ObtenerNombreWSResponse")]
        string ObtenerNombreWS();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInformeAccidenteWS/ObtenerNombreWS", ReplyAction="http://tempuri.org/IInformeAccidenteWS/ObtenerNombreWSResponse")]
        System.Threading.Tasks.Task<string> ObtenerNombreWSAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInformeAccidenteWS/Obtener", ReplyAction="http://tempuri.org/IInformeAccidenteWS/ObtenerResponse")]
        string Obtener(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInformeAccidenteWS/Obtener", ReplyAction="http://tempuri.org/IInformeAccidenteWS/ObtenerResponse")]
        System.Threading.Tasks.Task<string> ObtenerAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInformeAccidenteWS/Listar", ReplyAction="http://tempuri.org/IInformeAccidenteWS/ListarResponse")]
        string Listar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInformeAccidenteWS/Listar", ReplyAction="http://tempuri.org/IInformeAccidenteWS/ListarResponse")]
        System.Threading.Tasks.Task<string> ListarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInformeAccidenteWS/Buscar", ReplyAction="http://tempuri.org/IInformeAccidenteWS/BuscarResponse")]
        string Buscar(string numPoliza, string tipoSiniestro, string fechaSiniestro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInformeAccidenteWS/Buscar", ReplyAction="http://tempuri.org/IInformeAccidenteWS/BuscarResponse")]
        System.Threading.Tasks.Task<string> BuscarAsync(string numPoliza, string tipoSiniestro, string fechaSiniestro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInformeAccidenteWS/BuscarParaPresupuesto", ReplyAction="http://tempuri.org/IInformeAccidenteWS/BuscarParaPresupuestoResponse")]
        string BuscarParaPresupuesto(string numInforme, string asegurado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInformeAccidenteWS/BuscarParaPresupuesto", ReplyAction="http://tempuri.org/IInformeAccidenteWS/BuscarParaPresupuestoResponse")]
        System.Threading.Tasks.Task<string> BuscarParaPresupuestoAsync(string numInforme, string asegurado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInformeAccidenteWS/Agregar", ReplyAction="http://tempuri.org/IInformeAccidenteWS/AgregarResponse")]
        string Agregar(Pacifico.SINCO.EN.InformeAccidenteEN model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInformeAccidenteWS/Agregar", ReplyAction="http://tempuri.org/IInformeAccidenteWS/AgregarResponse")]
        System.Threading.Tasks.Task<string> AgregarAsync(Pacifico.SINCO.EN.InformeAccidenteEN model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInformeAccidenteWS/Modificar", ReplyAction="http://tempuri.org/IInformeAccidenteWS/ModificarResponse")]
        string Modificar(Pacifico.SINCO.EN.InformeAccidenteEN model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInformeAccidenteWS/Modificar", ReplyAction="http://tempuri.org/IInformeAccidenteWS/ModificarResponse")]
        System.Threading.Tasks.Task<string> ModificarAsync(Pacifico.SINCO.EN.InformeAccidenteEN model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInformeAccidenteWS/PendienteEvaluar", ReplyAction="http://tempuri.org/IInformeAccidenteWS/PendienteEvaluarResponse")]
        string PendienteEvaluar(int siniestroId, int tecnicoid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInformeAccidenteWS/PendienteEvaluar", ReplyAction="http://tempuri.org/IInformeAccidenteWS/PendienteEvaluarResponse")]
        System.Threading.Tasks.Task<string> PendienteEvaluarAsync(int siniestroId, int tecnicoid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInformeAccidenteWS/ReversaPendienteEvaluar", ReplyAction="http://tempuri.org/IInformeAccidenteWS/ReversaPendienteEvaluarResponse")]
        string ReversaPendienteEvaluar(int siniestroId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInformeAccidenteWS/ReversaPendienteEvaluar", ReplyAction="http://tempuri.org/IInformeAccidenteWS/ReversaPendienteEvaluarResponse")]
        System.Threading.Tasks.Task<string> ReversaPendienteEvaluarAsync(int siniestroId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInformeAccidenteWSChannel : Pacifico.SINCO.WEB.wsInformeAccidente.IInformeAccidenteWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InformeAccidenteWSClient : System.ServiceModel.ClientBase<Pacifico.SINCO.WEB.wsInformeAccidente.IInformeAccidenteWS>, Pacifico.SINCO.WEB.wsInformeAccidente.IInformeAccidenteWS {
        
        public InformeAccidenteWSClient() {
        }
        
        public InformeAccidenteWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InformeAccidenteWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InformeAccidenteWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InformeAccidenteWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ObtenerNombreWS() {
            return base.Channel.ObtenerNombreWS();
        }
        
        public System.Threading.Tasks.Task<string> ObtenerNombreWSAsync() {
            return base.Channel.ObtenerNombreWSAsync();
        }
        
        public string Obtener(int Id) {
            return base.Channel.Obtener(Id);
        }
        
        public System.Threading.Tasks.Task<string> ObtenerAsync(int Id) {
            return base.Channel.ObtenerAsync(Id);
        }
        
        public string Listar() {
            return base.Channel.Listar();
        }
        
        public System.Threading.Tasks.Task<string> ListarAsync() {
            return base.Channel.ListarAsync();
        }
        
        public string Buscar(string numPoliza, string tipoSiniestro, string fechaSiniestro) {
            return base.Channel.Buscar(numPoliza, tipoSiniestro, fechaSiniestro);
        }
        
        public System.Threading.Tasks.Task<string> BuscarAsync(string numPoliza, string tipoSiniestro, string fechaSiniestro) {
            return base.Channel.BuscarAsync(numPoliza, tipoSiniestro, fechaSiniestro);
        }
        
        public string BuscarParaPresupuesto(string numInforme, string asegurado) {
            return base.Channel.BuscarParaPresupuesto(numInforme, asegurado);
        }
        
        public System.Threading.Tasks.Task<string> BuscarParaPresupuestoAsync(string numInforme, string asegurado) {
            return base.Channel.BuscarParaPresupuestoAsync(numInforme, asegurado);
        }
        
        public string Agregar(Pacifico.SINCO.EN.InformeAccidenteEN model) {
            return base.Channel.Agregar(model);
        }
        
        public System.Threading.Tasks.Task<string> AgregarAsync(Pacifico.SINCO.EN.InformeAccidenteEN model) {
            return base.Channel.AgregarAsync(model);
        }
        
        public string Modificar(Pacifico.SINCO.EN.InformeAccidenteEN model) {
            return base.Channel.Modificar(model);
        }
        
        public System.Threading.Tasks.Task<string> ModificarAsync(Pacifico.SINCO.EN.InformeAccidenteEN model) {
            return base.Channel.ModificarAsync(model);
        }
        
        public string PendienteEvaluar(int siniestroId, int tecnicoid) {
            return base.Channel.PendienteEvaluar(siniestroId, tecnicoid);
        }
        
        public System.Threading.Tasks.Task<string> PendienteEvaluarAsync(int siniestroId, int tecnicoid) {
            return base.Channel.PendienteEvaluarAsync(siniestroId, tecnicoid);
        }
        
        public string ReversaPendienteEvaluar(int siniestroId) {
            return base.Channel.ReversaPendienteEvaluar(siniestroId);
        }
        
        public System.Threading.Tasks.Task<string> ReversaPendienteEvaluarAsync(int siniestroId) {
            return base.Channel.ReversaPendienteEvaluarAsync(siniestroId);
        }
    }
}
