//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.SINCO.WEB.wsInformeAccidente {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsInformeAccidente.IInformeAccidenteWS")]
    public interface IInformeAccidenteWS {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInformeAccidenteWS/ObtenerNombreWS", ReplyAction="http://tempuri.org/IInformeAccidenteWS/ObtenerNombreWSResponse")]
        string ObtenerNombreWS();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInformeAccidenteWS/ObtenerNombreWS", ReplyAction="http://tempuri.org/IInformeAccidenteWS/ObtenerNombreWSResponse")]
        System.Threading.Tasks.Task<string> ObtenerNombreWSAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInformeAccidenteWS/Obtener", ReplyAction="http://tempuri.org/IInformeAccidenteWS/ObtenerResponse")]
        string Obtener(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInformeAccidenteWS/Obtener", ReplyAction="http://tempuri.org/IInformeAccidenteWS/ObtenerResponse")]
        System.Threading.Tasks.Task<string> ObtenerAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInformeAccidenteWS/Listar", ReplyAction="http://tempuri.org/IInformeAccidenteWS/ListarResponse")]
        string Listar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInformeAccidenteWS/Listar", ReplyAction="http://tempuri.org/IInformeAccidenteWS/ListarResponse")]
        System.Threading.Tasks.Task<string> ListarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInformeAccidenteWS/Buscar", ReplyAction="http://tempuri.org/IInformeAccidenteWS/BuscarResponse")]
        string Buscar(string numPoliza, string tipoSiniestro, string fechaSiniestro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInformeAccidenteWS/Buscar", ReplyAction="http://tempuri.org/IInformeAccidenteWS/BuscarResponse")]
        System.Threading.Tasks.Task<string> BuscarAsync(string numPoliza, string tipoSiniestro, string fechaSiniestro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInformeAccidenteWS/BuscarParaPresupuesto", ReplyAction="http://tempuri.org/IInformeAccidenteWS/BuscarParaPresupuestoResponse")]
        string BuscarParaPresupuesto(string numInforme, string asegurado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInformeAccidenteWS/BuscarParaPresupuesto", ReplyAction="http://tempuri.org/IInformeAccidenteWS/BuscarParaPresupuestoResponse")]
        System.Threading.Tasks.Task<string> BuscarParaPresupuestoAsync(string numInforme, string asegurado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInformeAccidenteWS/Agregar", ReplyAction="http://tempuri.org/IInformeAccidenteWS/AgregarResponse")]
        string Agregar(Pacifico.SINCO.EN.InformeAccidenteEN model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInformeAccidenteWS/Agregar", ReplyAction="http://tempuri.org/IInformeAccidenteWS/AgregarResponse")]
        System.Threading.Tasks.Task<string> AgregarAsync(Pacifico.SINCO.EN.InformeAccidenteEN model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInformeAccidenteWS/Modificar", ReplyAction="http://tempuri.org/IInformeAccidenteWS/ModificarResponse")]
        string Modificar(Pacifico.SINCO.EN.InformeAccidenteEN model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInformeAccidenteWS/Modificar", ReplyAction="http://tempuri.org/IInformeAccidenteWS/ModificarResponse")]
        System.Threading.Tasks.Task<string> ModificarAsync(Pacifico.SINCO.EN.InformeAccidenteEN model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInformeAccidenteWS/PendienteEvaluar", ReplyAction="http://tempuri.org/IInformeAccidenteWS/PendienteEvaluarResponse")]
        string PendienteEvaluar(int siniestroId, int tecnicoid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInformeAccidenteWS/PendienteEvaluar", ReplyAction="http://tempuri.org/IInformeAccidenteWS/PendienteEvaluarResponse")]
        System.Threading.Tasks.Task<string> PendienteEvaluarAsync(int siniestroId, int tecnicoid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInformeAccidenteWS/ReversaPendienteEvaluar", ReplyAction="http://tempuri.org/IInformeAccidenteWS/ReversaPendienteEvaluarResponse")]
        string ReversaPendienteEvaluar(int siniestroId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInformeAccidenteWS/ReversaPendienteEvaluar", ReplyAction="http://tempuri.org/IInformeAccidenteWS/ReversaPendienteEvaluarResponse")]
        System.Threading.Tasks.Task<string> ReversaPendienteEvaluarAsync(int siniestroId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInformeAccidenteWS/RegistrarPresupuesto", ReplyAction="http://tempuri.org/IInformeAccidenteWS/RegistrarPresupuestoResponse")]
        string RegistrarPresupuesto(int informeid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInformeAccidenteWS/RegistrarPresupuesto", ReplyAction="http://tempuri.org/IInformeAccidenteWS/RegistrarPresupuestoResponse")]
        System.Threading.Tasks.Task<string> RegistrarPresupuestoAsync(int informeid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInformeAccidenteWSChannel : Pacifico.SINCO.WEB.wsInformeAccidente.IInformeAccidenteWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InformeAccidenteWSClient : System.ServiceModel.ClientBase<Pacifico.SINCO.WEB.wsInformeAccidente.IInformeAccidenteWS>, Pacifico.SINCO.WEB.wsInformeAccidente.IInformeAccidenteWS {
        
        public InformeAccidenteWSClient() {
        }
        
        public InformeAccidenteWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InformeAccidenteWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InformeAccidenteWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InformeAccidenteWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ObtenerNombreWS() {
            return base.Channel.ObtenerNombreWS();
        }
        
        public System.Threading.Tasks.Task<string> ObtenerNombreWSAsync() {
            return base.Channel.ObtenerNombreWSAsync();
        }
        
        public string Obtener(int Id) {
            return base.Channel.Obtener(Id);
        }
        
        public System.Threading.Tasks.Task<string> ObtenerAsync(int Id) {
            return base.Channel.ObtenerAsync(Id);
        }
        
        public string Listar() {
            return base.Channel.Listar();
        }
        
        public System.Threading.Tasks.Task<string> ListarAsync() {
            return base.Channel.ListarAsync();
        }
        
        public string Buscar(string numPoliza, string tipoSiniestro, string fechaSiniestro) {
            return base.Channel.Buscar(numPoliza, tipoSiniestro, fechaSiniestro);
        }
        
        public System.Threading.Tasks.Task<string> BuscarAsync(string numPoliza, string tipoSiniestro, string fechaSiniestro) {
            return base.Channel.BuscarAsync(numPoliza, tipoSiniestro, fechaSiniestro);
        }
        
        public string BuscarParaPresupuesto(string numInforme, string asegurado) {
            return base.Channel.BuscarParaPresupuesto(numInforme, asegurado);
        }
        
        public System.Threading.Tasks.Task<string> BuscarParaPresupuestoAsync(string numInforme, string asegurado) {
            return base.Channel.BuscarParaPresupuestoAsync(numInforme, asegurado);
        }
        
        public string Agregar(Pacifico.SINCO.EN.InformeAccidenteEN model) {
            return base.Channel.Agregar(model);
        }
        
        public System.Threading.Tasks.Task<string> AgregarAsync(Pacifico.SINCO.EN.InformeAccidenteEN model) {
            return base.Channel.AgregarAsync(model);
        }
        
        public string Modificar(Pacifico.SINCO.EN.InformeAccidenteEN model) {
            return base.Channel.Modificar(model);
        }
        
        public System.Threading.Tasks.Task<string> ModificarAsync(Pacifico.SINCO.EN.InformeAccidenteEN model) {
            return base.Channel.ModificarAsync(model);
        }
        
        public string PendienteEvaluar(int siniestroId, int tecnicoid) {
            return base.Channel.PendienteEvaluar(siniestroId, tecnicoid);
        }
        
        public System.Threading.Tasks.Task<string> PendienteEvaluarAsync(int siniestroId, int tecnicoid) {
            return base.Channel.PendienteEvaluarAsync(siniestroId, tecnicoid);
        }
        
        public string ReversaPendienteEvaluar(int siniestroId) {
            return base.Channel.ReversaPendienteEvaluar(siniestroId);
        }
        
        public System.Threading.Tasks.Task<string> ReversaPendienteEvaluarAsync(int siniestroId) {
            return base.Channel.ReversaPendienteEvaluarAsync(siniestroId);
        }
        
        public string RegistrarPresupuesto(int informeid) {
            return base.Channel.RegistrarPresupuesto(informeid);
        }
        
        public System.Threading.Tasks.Task<string> RegistrarPresupuestoAsync(int informeid) {
            return base.Channel.RegistrarPresupuestoAsync(informeid);
        }
    }
}
