//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.SINCO.WEB.wsUtil {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsUtil.IUtilWS")]
    public interface IUtilWS {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUtilWS/wsObtenerNombreWS", ReplyAction="http://tempuri.org/IUtilWS/wsObtenerNombreWSResponse")]
        string wsObtenerNombreWS();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUtilWS/wsObtenerNombreWS", ReplyAction="http://tempuri.org/IUtilWS/wsObtenerNombreWSResponse")]
        System.Threading.Tasks.Task<string> wsObtenerNombreWSAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUtilWS/ListarPoliza", ReplyAction="http://tempuri.org/IUtilWS/ListarPolizaResponse")]
        Pacifico.SINCO.EN.enPoliza[] ListarPoliza(Pacifico.SINCO.EN.enPoliza pEnPoliza);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUtilWS/ListarPoliza", ReplyAction="http://tempuri.org/IUtilWS/ListarPolizaResponse")]
        System.Threading.Tasks.Task<Pacifico.SINCO.EN.enPoliza[]> ListarPolizaAsync(Pacifico.SINCO.EN.enPoliza pEnPoliza);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUtilWS/ListarProcurador", ReplyAction="http://tempuri.org/IUtilWS/ListarProcuradorResponse")]
        Pacifico.SINCO.EN.enProcurador[] ListarProcurador(Pacifico.SINCO.EN.enProcurador pEnProcurador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUtilWS/ListarProcurador", ReplyAction="http://tempuri.org/IUtilWS/ListarProcuradorResponse")]
        System.Threading.Tasks.Task<Pacifico.SINCO.EN.enProcurador[]> ListarProcuradorAsync(Pacifico.SINCO.EN.enProcurador pEnProcurador);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUtilWSChannel : Pacifico.SINCO.WEB.wsUtil.IUtilWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UtilWSClient : System.ServiceModel.ClientBase<Pacifico.SINCO.WEB.wsUtil.IUtilWS>, Pacifico.SINCO.WEB.wsUtil.IUtilWS {
        
        public UtilWSClient() {
        }
        
        public UtilWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UtilWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UtilWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UtilWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string wsObtenerNombreWS() {
            return base.Channel.wsObtenerNombreWS();
        }
        
        public System.Threading.Tasks.Task<string> wsObtenerNombreWSAsync() {
            return base.Channel.wsObtenerNombreWSAsync();
        }
        
        public Pacifico.SINCO.EN.enPoliza[] ListarPoliza(Pacifico.SINCO.EN.enPoliza pEnPoliza) {
            return base.Channel.ListarPoliza(pEnPoliza);
        }
        
        public System.Threading.Tasks.Task<Pacifico.SINCO.EN.enPoliza[]> ListarPolizaAsync(Pacifico.SINCO.EN.enPoliza pEnPoliza) {
            return base.Channel.ListarPolizaAsync(pEnPoliza);
        }
        
        public Pacifico.SINCO.EN.enProcurador[] ListarProcurador(Pacifico.SINCO.EN.enProcurador pEnProcurador) {
            return base.Channel.ListarProcurador(pEnProcurador);
        }
        
        public System.Threading.Tasks.Task<Pacifico.SINCO.EN.enProcurador[]> ListarProcuradorAsync(Pacifico.SINCO.EN.enProcurador pEnProcurador) {
            return base.Channel.ListarProcuradorAsync(pEnProcurador);
        }
    }
}
