//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.SINCO.WEB.wsUtil {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsUtil.IUtilWS")]
    public interface IUtilWS {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUtilWS/wsObtenerNombreWS", ReplyAction="http://tempuri.org/IUtilWS/wsObtenerNombreWSResponse")]
        string wsObtenerNombreWS();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUtilWS/wsObtenerNombreWS", ReplyAction="http://tempuri.org/IUtilWS/wsObtenerNombreWSResponse")]
        System.Threading.Tasks.Task<string> wsObtenerNombreWSAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUtilWS/ListarPoliza", ReplyAction="http://tempuri.org/IUtilWS/ListarPolizaResponse")]
        string ListarPoliza();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUtilWS/ListarPoliza", ReplyAction="http://tempuri.org/IUtilWS/ListarPolizaResponse")]
        System.Threading.Tasks.Task<string> ListarPolizaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUtilWS/BuscarPoliza", ReplyAction="http://tempuri.org/IUtilWS/BuscarPolizaResponse")]
        string BuscarPoliza(string dniAsegurado, string numPoliza, string placa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUtilWS/BuscarPoliza", ReplyAction="http://tempuri.org/IUtilWS/BuscarPolizaResponse")]
        System.Threading.Tasks.Task<string> BuscarPolizaAsync(string dniAsegurado, string numPoliza, string placa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUtilWS/ListarProcurador", ReplyAction="http://tempuri.org/IUtilWS/ListarProcuradorResponse")]
        string ListarProcurador();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUtilWS/ListarProcurador", ReplyAction="http://tempuri.org/IUtilWS/ListarProcuradorResponse")]
        System.Threading.Tasks.Task<string> ListarProcuradorAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUtilWS/BuscarProcurador", ReplyAction="http://tempuri.org/IUtilWS/BuscarProcuradorResponse")]
        string BuscarProcurador(string numProcurador, string procurador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUtilWS/BuscarProcurador", ReplyAction="http://tempuri.org/IUtilWS/BuscarProcuradorResponse")]
        System.Threading.Tasks.Task<string> BuscarProcuradorAsync(string numProcurador, string procurador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUtilWS/ActualizaDisponibilidadProcurador", ReplyAction="http://tempuri.org/IUtilWS/ActualizaDisponibilidadProcuradorResponse")]
        string ActualizaDisponibilidadProcurador(Pacifico.SINCO.EN.ProcuradorEN pEnProcurador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUtilWS/ActualizaDisponibilidadProcurador", ReplyAction="http://tempuri.org/IUtilWS/ActualizaDisponibilidadProcuradorResponse")]
        System.Threading.Tasks.Task<string> ActualizaDisponibilidadProcuradorAsync(Pacifico.SINCO.EN.ProcuradorEN pEnProcurador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUtilWS/ObtenerProcurador", ReplyAction="http://tempuri.org/IUtilWS/ObtenerProcuradorResponse")]
        string ObtenerProcurador(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUtilWS/ObtenerProcurador", ReplyAction="http://tempuri.org/IUtilWS/ObtenerProcuradorResponse")]
        System.Threading.Tasks.Task<string> ObtenerProcuradorAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUtilWSChannel : Pacifico.SINCO.WEB.wsUtil.IUtilWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UtilWSClient : System.ServiceModel.ClientBase<Pacifico.SINCO.WEB.wsUtil.IUtilWS>, Pacifico.SINCO.WEB.wsUtil.IUtilWS {
        
        public UtilWSClient() {
        }
        
        public UtilWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UtilWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UtilWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UtilWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string wsObtenerNombreWS() {
            return base.Channel.wsObtenerNombreWS();
        }
        
        public System.Threading.Tasks.Task<string> wsObtenerNombreWSAsync() {
            return base.Channel.wsObtenerNombreWSAsync();
        }
        
        public string ListarPoliza() {
            return base.Channel.ListarPoliza();
        }
        
        public System.Threading.Tasks.Task<string> ListarPolizaAsync() {
            return base.Channel.ListarPolizaAsync();
        }
        
        public string BuscarPoliza(string dniAsegurado, string numPoliza, string placa) {
            return base.Channel.BuscarPoliza(dniAsegurado, numPoliza, placa);
        }
        
        public System.Threading.Tasks.Task<string> BuscarPolizaAsync(string dniAsegurado, string numPoliza, string placa) {
            return base.Channel.BuscarPolizaAsync(dniAsegurado, numPoliza, placa);
        }
        
        public string ListarProcurador() {
            return base.Channel.ListarProcurador();
        }
        
        public System.Threading.Tasks.Task<string> ListarProcuradorAsync() {
            return base.Channel.ListarProcuradorAsync();
        }
        
        public string BuscarProcurador(string numProcurador, string procurador) {
            return base.Channel.BuscarProcurador(numProcurador, procurador);
        }
        
        public System.Threading.Tasks.Task<string> BuscarProcuradorAsync(string numProcurador, string procurador) {
            return base.Channel.BuscarProcuradorAsync(numProcurador, procurador);
        }
        
        public string ActualizaDisponibilidadProcurador(Pacifico.SINCO.EN.ProcuradorEN pEnProcurador) {
            return base.Channel.ActualizaDisponibilidadProcurador(pEnProcurador);
        }
        
        public System.Threading.Tasks.Task<string> ActualizaDisponibilidadProcuradorAsync(Pacifico.SINCO.EN.ProcuradorEN pEnProcurador) {
            return base.Channel.ActualizaDisponibilidadProcuradorAsync(pEnProcurador);
        }
        
        public string ObtenerProcurador(int id) {
            return base.Channel.ObtenerProcurador(id);
        }
        
        public System.Threading.Tasks.Task<string> ObtenerProcuradorAsync(int id) {
            return base.Channel.ObtenerProcuradorAsync(id);
        }
    }
}
