//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18408
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.SINCO.WEB.wsPresupuesto {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsPresupuesto.IwsPresupuesto")]
    public interface IwsPresupuesto {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsPresupuesto/wsObtenerNombreWS", ReplyAction="http://tempuri.org/IwsPresupuesto/wsObtenerNombreWSResponse")]
        string wsObtenerNombreWS();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsPresupuesto/wsObtenerNombreWS", ReplyAction="http://tempuri.org/IwsPresupuesto/wsObtenerNombreWSResponse")]
        System.Threading.Tasks.Task<string> wsObtenerNombreWSAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IwsPresupuestoChannel : Pacifico.SINCO.WEB.wsPresupuesto.IwsPresupuesto, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IwsPresupuestoClient : System.ServiceModel.ClientBase<Pacifico.SINCO.WEB.wsPresupuesto.IwsPresupuesto>, Pacifico.SINCO.WEB.wsPresupuesto.IwsPresupuesto {
        
        public IwsPresupuestoClient() {
        }
        
        public IwsPresupuestoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IwsPresupuestoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IwsPresupuestoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IwsPresupuestoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string wsObtenerNombreWS() {
            return base.Channel.wsObtenerNombreWS();
        }
        
        public System.Threading.Tasks.Task<string> wsObtenerNombreWSAsync() {
            return base.Channel.wsObtenerNombreWSAsync();
        }
    }
}
