//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.SINCO.WEB.wsTecnico {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsTecnico.ITecnicoWS")]
    public interface ITecnicoWS {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITecnicoWS/wsObtenerNombreWS", ReplyAction="http://tempuri.org/ITecnicoWS/wsObtenerNombreWSResponse")]
        string wsObtenerNombreWS();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITecnicoWS/wsObtenerNombreWS", ReplyAction="http://tempuri.org/ITecnicoWS/wsObtenerNombreWSResponse")]
        System.Threading.Tasks.Task<string> wsObtenerNombreWSAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITecnicoWS/Obtener", ReplyAction="http://tempuri.org/ITecnicoWS/ObtenerResponse")]
        string Obtener(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITecnicoWS/Obtener", ReplyAction="http://tempuri.org/ITecnicoWS/ObtenerResponse")]
        System.Threading.Tasks.Task<string> ObtenerAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITecnicoWS/Listar", ReplyAction="http://tempuri.org/ITecnicoWS/ListarResponse")]
        string Listar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITecnicoWS/Listar", ReplyAction="http://tempuri.org/ITecnicoWS/ListarResponse")]
        System.Threading.Tasks.Task<string> ListarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITecnicoWS/ConsultarDisponibilidad", ReplyAction="http://tempuri.org/ITecnicoWS/ConsultarDisponibilidadResponse")]
        string ConsultarDisponibilidad(string codigoTecnico, string tecnico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITecnicoWS/ConsultarDisponibilidad", ReplyAction="http://tempuri.org/ITecnicoWS/ConsultarDisponibilidadResponse")]
        System.Threading.Tasks.Task<string> ConsultarDisponibilidadAsync(string codigoTecnico, string tecnico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITecnicoWS/ActualizaDisponibilidad", ReplyAction="http://tempuri.org/ITecnicoWS/ActualizaDisponibilidadResponse")]
        string ActualizaDisponibilidad(Pacifico.SINCO.EN.TecnicoEN tecnico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITecnicoWS/ActualizaDisponibilidad", ReplyAction="http://tempuri.org/ITecnicoWS/ActualizaDisponibilidadResponse")]
        System.Threading.Tasks.Task<string> ActualizaDisponibilidadAsync(Pacifico.SINCO.EN.TecnicoEN tecnico);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITecnicoWSChannel : Pacifico.SINCO.WEB.wsTecnico.ITecnicoWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TecnicoWSClient : System.ServiceModel.ClientBase<Pacifico.SINCO.WEB.wsTecnico.ITecnicoWS>, Pacifico.SINCO.WEB.wsTecnico.ITecnicoWS {
        
        public TecnicoWSClient() {
        }
        
        public TecnicoWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TecnicoWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TecnicoWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TecnicoWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string wsObtenerNombreWS() {
            return base.Channel.wsObtenerNombreWS();
        }
        
        public System.Threading.Tasks.Task<string> wsObtenerNombreWSAsync() {
            return base.Channel.wsObtenerNombreWSAsync();
        }
        
        public string Obtener(int id) {
            return base.Channel.Obtener(id);
        }
        
        public System.Threading.Tasks.Task<string> ObtenerAsync(int id) {
            return base.Channel.ObtenerAsync(id);
        }
        
        public string Listar() {
            return base.Channel.Listar();
        }
        
        public System.Threading.Tasks.Task<string> ListarAsync() {
            return base.Channel.ListarAsync();
        }
        
        public string ConsultarDisponibilidad(string codigoTecnico, string tecnico) {
            return base.Channel.ConsultarDisponibilidad(codigoTecnico, tecnico);
        }
        
        public System.Threading.Tasks.Task<string> ConsultarDisponibilidadAsync(string codigoTecnico, string tecnico) {
            return base.Channel.ConsultarDisponibilidadAsync(codigoTecnico, tecnico);
        }
        
        public string ActualizaDisponibilidad(Pacifico.SINCO.EN.TecnicoEN tecnico) {
            return base.Channel.ActualizaDisponibilidad(tecnico);
        }
        
        public System.Threading.Tasks.Task<string> ActualizaDisponibilidadAsync(Pacifico.SINCO.EN.TecnicoEN tecnico) {
            return base.Channel.ActualizaDisponibilidadAsync(tecnico);
        }
    }
}
