//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.SINCO.WEB.wsLiquidacion {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsLiquidacion.ILiquidacionWS")]
    public interface ILiquidacionWS {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILiquidacionWS/ObtenerNombreWS", ReplyAction="http://tempuri.org/ILiquidacionWS/ObtenerNombreWSResponse")]
        string ObtenerNombreWS();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILiquidacionWS/ObtenerNombreWS", ReplyAction="http://tempuri.org/ILiquidacionWS/ObtenerNombreWSResponse")]
        System.Threading.Tasks.Task<string> ObtenerNombreWSAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILiquidacionWS/Obtener", ReplyAction="http://tempuri.org/ILiquidacionWS/ObtenerResponse")]
        string Obtener(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILiquidacionWS/Obtener", ReplyAction="http://tempuri.org/ILiquidacionWS/ObtenerResponse")]
        System.Threading.Tasks.Task<string> ObtenerAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILiquidacionWS/Listar", ReplyAction="http://tempuri.org/ILiquidacionWS/ListarResponse")]
        string Listar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILiquidacionWS/Listar", ReplyAction="http://tempuri.org/ILiquidacionWS/ListarResponse")]
        System.Threading.Tasks.Task<string> ListarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILiquidacionWS/Buscar", ReplyAction="http://tempuri.org/ILiquidacionWS/BuscarResponse")]
        string Buscar(string numLiquidacion, string tipoSiniestro, string fechaLiquidacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILiquidacionWS/Buscar", ReplyAction="http://tempuri.org/ILiquidacionWS/BuscarResponse")]
        System.Threading.Tasks.Task<string> BuscarAsync(string numLiquidacion, string tipoSiniestro, string fechaLiquidacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILiquidacionWS/Agregar", ReplyAction="http://tempuri.org/ILiquidacionWS/AgregarResponse")]
        string Agregar(Pacifico.SINCO.EN.LiquidacionEN model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILiquidacionWS/Agregar", ReplyAction="http://tempuri.org/ILiquidacionWS/AgregarResponse")]
        System.Threading.Tasks.Task<string> AgregarAsync(Pacifico.SINCO.EN.LiquidacionEN model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILiquidacionWS/Modificar", ReplyAction="http://tempuri.org/ILiquidacionWS/ModificarResponse")]
        string Modificar(Pacifico.SINCO.EN.LiquidacionEN model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILiquidacionWS/Modificar", ReplyAction="http://tempuri.org/ILiquidacionWS/ModificarResponse")]
        System.Threading.Tasks.Task<string> ModificarAsync(Pacifico.SINCO.EN.LiquidacionEN model);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILiquidacionWSChannel : Pacifico.SINCO.WEB.wsLiquidacion.ILiquidacionWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LiquidacionWSClient : System.ServiceModel.ClientBase<Pacifico.SINCO.WEB.wsLiquidacion.ILiquidacionWS>, Pacifico.SINCO.WEB.wsLiquidacion.ILiquidacionWS {
        
        public LiquidacionWSClient() {
        }
        
        public LiquidacionWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LiquidacionWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LiquidacionWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LiquidacionWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ObtenerNombreWS() {
            return base.Channel.ObtenerNombreWS();
        }
        
        public System.Threading.Tasks.Task<string> ObtenerNombreWSAsync() {
            return base.Channel.ObtenerNombreWSAsync();
        }
        
        public string Obtener(int Id) {
            return base.Channel.Obtener(Id);
        }
        
        public System.Threading.Tasks.Task<string> ObtenerAsync(int Id) {
            return base.Channel.ObtenerAsync(Id);
        }
        
        public string Listar() {
            return base.Channel.Listar();
        }
        
        public System.Threading.Tasks.Task<string> ListarAsync() {
            return base.Channel.ListarAsync();
        }
        
        public string Buscar(string numLiquidacion, string tipoSiniestro, string fechaLiquidacion) {
            return base.Channel.Buscar(numLiquidacion, tipoSiniestro, fechaLiquidacion);
        }
        
        public System.Threading.Tasks.Task<string> BuscarAsync(string numLiquidacion, string tipoSiniestro, string fechaLiquidacion) {
            return base.Channel.BuscarAsync(numLiquidacion, tipoSiniestro, fechaLiquidacion);
        }
        
        public string Agregar(Pacifico.SINCO.EN.LiquidacionEN model) {
            return base.Channel.Agregar(model);
        }
        
        public System.Threading.Tasks.Task<string> AgregarAsync(Pacifico.SINCO.EN.LiquidacionEN model) {
            return base.Channel.AgregarAsync(model);
        }
        
        public string Modificar(Pacifico.SINCO.EN.LiquidacionEN model) {
            return base.Channel.Modificar(model);
        }
        
        public System.Threading.Tasks.Task<string> ModificarAsync(Pacifico.SINCO.EN.LiquidacionEN model) {
            return base.Channel.ModificarAsync(model);
        }
    }
}
