//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18408
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.SINCO.WEB.wsSiniestro {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsSiniestro.IwsSiniestro")]
    public interface IwsSiniestro {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSiniestro/wsObtenerNombreWS", ReplyAction="http://tempuri.org/IwsSiniestro/wsObtenerNombreWSResponse")]
        string wsObtenerNombreWS();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsSiniestro/wsObtenerNombreWS", ReplyAction="http://tempuri.org/IwsSiniestro/wsObtenerNombreWSResponse")]
        System.Threading.Tasks.Task<string> wsObtenerNombreWSAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IwsSiniestroChannel : Pacifico.SINCO.WEB.wsSiniestro.IwsSiniestro, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IwsSiniestroClient : System.ServiceModel.ClientBase<Pacifico.SINCO.WEB.wsSiniestro.IwsSiniestro>, Pacifico.SINCO.WEB.wsSiniestro.IwsSiniestro {
        
        public IwsSiniestroClient() {
        }
        
        public IwsSiniestroClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IwsSiniestroClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IwsSiniestroClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IwsSiniestroClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string wsObtenerNombreWS() {
            return base.Channel.wsObtenerNombreWS();
        }
        
        public System.Threading.Tasks.Task<string> wsObtenerNombreWSAsync() {
            return base.Channel.wsObtenerNombreWSAsync();
        }
    }
}
