//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.SINCO.WEB.wsSiniestro {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsSiniestro.ISiniestroWS")]
    public interface ISiniestroWS {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISiniestroWS/wsObtenerNombreWS", ReplyAction="http://tempuri.org/ISiniestroWS/wsObtenerNombreWSResponse")]
        string wsObtenerNombreWS();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISiniestroWS/wsObtenerNombreWS", ReplyAction="http://tempuri.org/ISiniestroWS/wsObtenerNombreWSResponse")]
        System.Threading.Tasks.Task<string> wsObtenerNombreWSAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISiniestroWS/ListarSiniestro", ReplyAction="http://tempuri.org/ISiniestroWS/ListarSiniestroResponse")]
        Pacifico.SINCO.EN.enSiniestro[] ListarSiniestro(Pacifico.SINCO.EN.enSiniestro pEnSiniestro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISiniestroWS/ListarSiniestro", ReplyAction="http://tempuri.org/ISiniestroWS/ListarSiniestroResponse")]
        System.Threading.Tasks.Task<Pacifico.SINCO.EN.enSiniestro[]> ListarSiniestroAsync(Pacifico.SINCO.EN.enSiniestro pEnSiniestro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISiniestroWS/ObtenerSiniestro", ReplyAction="http://tempuri.org/ISiniestroWS/ObtenerSiniestroResponse")]
        Pacifico.SINCO.EN.enSiniestro ObtenerSiniestro(Pacifico.SINCO.EN.enSiniestro pEnSiniestro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISiniestroWS/ObtenerSiniestro", ReplyAction="http://tempuri.org/ISiniestroWS/ObtenerSiniestroResponse")]
        System.Threading.Tasks.Task<Pacifico.SINCO.EN.enSiniestro> ObtenerSiniestroAsync(Pacifico.SINCO.EN.enSiniestro pEnSiniestro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISiniestroWS/IngresarSiniestro", ReplyAction="http://tempuri.org/ISiniestroWS/IngresarSiniestroResponse")]
        bool IngresarSiniestro(Pacifico.SINCO.EN.enSiniestro pEnSiniestro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISiniestroWS/IngresarSiniestro", ReplyAction="http://tempuri.org/ISiniestroWS/IngresarSiniestroResponse")]
        System.Threading.Tasks.Task<bool> IngresarSiniestroAsync(Pacifico.SINCO.EN.enSiniestro pEnSiniestro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISiniestroWS/ActualizaSiniestro", ReplyAction="http://tempuri.org/ISiniestroWS/ActualizaSiniestroResponse")]
        bool ActualizaSiniestro(Pacifico.SINCO.EN.enSiniestro pEnSiniestro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISiniestroWS/ActualizaSiniestro", ReplyAction="http://tempuri.org/ISiniestroWS/ActualizaSiniestroResponse")]
        System.Threading.Tasks.Task<bool> ActualizaSiniestroAsync(Pacifico.SINCO.EN.enSiniestro pEnSiniestro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISiniestroWS/ProcesarSiniestro", ReplyAction="http://tempuri.org/ISiniestroWS/ProcesarSiniestroResponse")]
        bool ProcesarSiniestro(Pacifico.SINCO.EN.enSiniestro pEnSiniestro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISiniestroWS/ProcesarSiniestro", ReplyAction="http://tempuri.org/ISiniestroWS/ProcesarSiniestroResponse")]
        System.Threading.Tasks.Task<bool> ProcesarSiniestroAsync(Pacifico.SINCO.EN.enSiniestro pEnSiniestro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISiniestroWS/RegistrarSiniestroPendiente", ReplyAction="http://tempuri.org/ISiniestroWS/RegistrarSiniestroPendienteResponse")]
        bool RegistrarSiniestroPendiente(Pacifico.SINCO.EN.enSiniestro pEnSiniestro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISiniestroWS/RegistrarSiniestroPendiente", ReplyAction="http://tempuri.org/ISiniestroWS/RegistrarSiniestroPendienteResponse")]
        System.Threading.Tasks.Task<bool> RegistrarSiniestroPendienteAsync(Pacifico.SINCO.EN.enSiniestro pEnSiniestro);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISiniestroWSChannel : Pacifico.SINCO.WEB.wsSiniestro.ISiniestroWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SiniestroWSClient : System.ServiceModel.ClientBase<Pacifico.SINCO.WEB.wsSiniestro.ISiniestroWS>, Pacifico.SINCO.WEB.wsSiniestro.ISiniestroWS {
        
        public SiniestroWSClient() {
        }
        
        public SiniestroWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SiniestroWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SiniestroWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SiniestroWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string wsObtenerNombreWS() {
            return base.Channel.wsObtenerNombreWS();
        }
        
        public System.Threading.Tasks.Task<string> wsObtenerNombreWSAsync() {
            return base.Channel.wsObtenerNombreWSAsync();
        }
        
        public Pacifico.SINCO.EN.enSiniestro[] ListarSiniestro(Pacifico.SINCO.EN.enSiniestro pEnSiniestro) {
            return base.Channel.ListarSiniestro(pEnSiniestro);
        }
        
        public System.Threading.Tasks.Task<Pacifico.SINCO.EN.enSiniestro[]> ListarSiniestroAsync(Pacifico.SINCO.EN.enSiniestro pEnSiniestro) {
            return base.Channel.ListarSiniestroAsync(pEnSiniestro);
        }
        
        public Pacifico.SINCO.EN.enSiniestro ObtenerSiniestro(Pacifico.SINCO.EN.enSiniestro pEnSiniestro) {
            return base.Channel.ObtenerSiniestro(pEnSiniestro);
        }
        
        public System.Threading.Tasks.Task<Pacifico.SINCO.EN.enSiniestro> ObtenerSiniestroAsync(Pacifico.SINCO.EN.enSiniestro pEnSiniestro) {
            return base.Channel.ObtenerSiniestroAsync(pEnSiniestro);
        }
        
        public bool IngresarSiniestro(Pacifico.SINCO.EN.enSiniestro pEnSiniestro) {
            return base.Channel.IngresarSiniestro(pEnSiniestro);
        }
        
        public System.Threading.Tasks.Task<bool> IngresarSiniestroAsync(Pacifico.SINCO.EN.enSiniestro pEnSiniestro) {
            return base.Channel.IngresarSiniestroAsync(pEnSiniestro);
        }
        
        public bool ActualizaSiniestro(Pacifico.SINCO.EN.enSiniestro pEnSiniestro) {
            return base.Channel.ActualizaSiniestro(pEnSiniestro);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizaSiniestroAsync(Pacifico.SINCO.EN.enSiniestro pEnSiniestro) {
            return base.Channel.ActualizaSiniestroAsync(pEnSiniestro);
        }
        
        public bool ProcesarSiniestro(Pacifico.SINCO.EN.enSiniestro pEnSiniestro) {
            return base.Channel.ProcesarSiniestro(pEnSiniestro);
        }
        
        public System.Threading.Tasks.Task<bool> ProcesarSiniestroAsync(Pacifico.SINCO.EN.enSiniestro pEnSiniestro) {
            return base.Channel.ProcesarSiniestroAsync(pEnSiniestro);
        }
        
        public bool RegistrarSiniestroPendiente(Pacifico.SINCO.EN.enSiniestro pEnSiniestro) {
            return base.Channel.RegistrarSiniestroPendiente(pEnSiniestro);
        }
        
        public System.Threading.Tasks.Task<bool> RegistrarSiniestroPendienteAsync(Pacifico.SINCO.EN.enSiniestro pEnSiniestro) {
            return base.Channel.RegistrarSiniestroPendienteAsync(pEnSiniestro);
        }
    }
}
