//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.SINCO.WEB.wsSiniestro {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsSiniestro.ISiniestroWS")]
    public interface ISiniestroWS {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISiniestroWS/wsObtenerNombreWS", ReplyAction="http://tempuri.org/ISiniestroWS/wsObtenerNombreWSResponse")]
        string wsObtenerNombreWS();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISiniestroWS/wsObtenerNombreWS", ReplyAction="http://tempuri.org/ISiniestroWS/wsObtenerNombreWSResponse")]
        System.Threading.Tasks.Task<string> wsObtenerNombreWSAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISiniestroWS/Listar", ReplyAction="http://tempuri.org/ISiniestroWS/ListarResponse")]
        string Listar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISiniestroWS/Listar", ReplyAction="http://tempuri.org/ISiniestroWS/ListarResponse")]
        System.Threading.Tasks.Task<string> ListarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISiniestroWS/Buscar", ReplyAction="http://tempuri.org/ISiniestroWS/BuscarResponse")]
        string Buscar(string numPoliza, string tipo, string fecRegistro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISiniestroWS/Buscar", ReplyAction="http://tempuri.org/ISiniestroWS/BuscarResponse")]
        System.Threading.Tasks.Task<string> BuscarAsync(string numPoliza, string tipo, string fecRegistro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISiniestroWS/Obtener", ReplyAction="http://tempuri.org/ISiniestroWS/ObtenerResponse")]
        string Obtener(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISiniestroWS/Obtener", ReplyAction="http://tempuri.org/ISiniestroWS/ObtenerResponse")]
        System.Threading.Tasks.Task<string> ObtenerAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISiniestroWS/Ingresar", ReplyAction="http://tempuri.org/ISiniestroWS/IngresarResponse")]
        string Ingresar(Pacifico.SINCO.EN.SiniestroEN siniestro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISiniestroWS/Ingresar", ReplyAction="http://tempuri.org/ISiniestroWS/IngresarResponse")]
        System.Threading.Tasks.Task<string> IngresarAsync(Pacifico.SINCO.EN.SiniestroEN siniestro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISiniestroWS/Actualizar", ReplyAction="http://tempuri.org/ISiniestroWS/ActualizarResponse")]
        string Actualizar(Pacifico.SINCO.EN.SiniestroEN siniestro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISiniestroWS/Actualizar", ReplyAction="http://tempuri.org/ISiniestroWS/ActualizarResponse")]
        System.Threading.Tasks.Task<string> ActualizarAsync(Pacifico.SINCO.EN.SiniestroEN siniestro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISiniestroWS/RegistrarProceso", ReplyAction="http://tempuri.org/ISiniestroWS/RegistrarProcesoResponse")]
        string RegistrarProceso(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISiniestroWS/RegistrarProceso", ReplyAction="http://tempuri.org/ISiniestroWS/RegistrarProcesoResponse")]
        System.Threading.Tasks.Task<string> RegistrarProcesoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISiniestroWS/RegistrarPendiente", ReplyAction="http://tempuri.org/ISiniestroWS/RegistrarPendienteResponse")]
        string RegistrarPendiente(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISiniestroWS/RegistrarPendiente", ReplyAction="http://tempuri.org/ISiniestroWS/RegistrarPendienteResponse")]
        System.Threading.Tasks.Task<string> RegistrarPendienteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISiniestroWS/Consultar", ReplyAction="http://tempuri.org/ISiniestroWS/ConsultarResponse")]
        string Consultar(string numSiniestro, string tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISiniestroWS/Consultar", ReplyAction="http://tempuri.org/ISiniestroWS/ConsultarResponse")]
        System.Threading.Tasks.Task<string> ConsultarAsync(string numSiniestro, string tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISiniestroWS/Aperturar", ReplyAction="http://tempuri.org/ISiniestroWS/AperturarResponse")]
        string Aperturar(Pacifico.SINCO.EN.SiniestroEN siniestro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISiniestroWS/Aperturar", ReplyAction="http://tempuri.org/ISiniestroWS/AperturarResponse")]
        System.Threading.Tasks.Task<string> AperturarAsync(Pacifico.SINCO.EN.SiniestroEN siniestro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISiniestroWS/RegistrarAsistido", ReplyAction="http://tempuri.org/ISiniestroWS/RegistrarAsistidoResponse")]
        string RegistrarAsistido(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISiniestroWS/RegistrarAsistido", ReplyAction="http://tempuri.org/ISiniestroWS/RegistrarAsistidoResponse")]
        System.Threading.Tasks.Task<string> RegistrarAsistidoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISiniestroWS/RegistrarAprobado", ReplyAction="http://tempuri.org/ISiniestroWS/RegistrarAprobadoResponse")]
        string RegistrarAprobado(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISiniestroWS/RegistrarAprobado", ReplyAction="http://tempuri.org/ISiniestroWS/RegistrarAprobadoResponse")]
        System.Threading.Tasks.Task<string> RegistrarAprobadoAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISiniestroWSChannel : Pacifico.SINCO.WEB.wsSiniestro.ISiniestroWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SiniestroWSClient : System.ServiceModel.ClientBase<Pacifico.SINCO.WEB.wsSiniestro.ISiniestroWS>, Pacifico.SINCO.WEB.wsSiniestro.ISiniestroWS {
        
        public SiniestroWSClient() {
        }
        
        public SiniestroWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SiniestroWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SiniestroWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SiniestroWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string wsObtenerNombreWS() {
            return base.Channel.wsObtenerNombreWS();
        }
        
        public System.Threading.Tasks.Task<string> wsObtenerNombreWSAsync() {
            return base.Channel.wsObtenerNombreWSAsync();
        }
        
        public string Listar() {
            return base.Channel.Listar();
        }
        
        public System.Threading.Tasks.Task<string> ListarAsync() {
            return base.Channel.ListarAsync();
        }
        
        public string Buscar(string numPoliza, string tipo, string fecRegistro) {
            return base.Channel.Buscar(numPoliza, tipo, fecRegistro);
        }
        
        public System.Threading.Tasks.Task<string> BuscarAsync(string numPoliza, string tipo, string fecRegistro) {
            return base.Channel.BuscarAsync(numPoliza, tipo, fecRegistro);
        }
        
        public string Obtener(int id) {
            return base.Channel.Obtener(id);
        }
        
        public System.Threading.Tasks.Task<string> ObtenerAsync(int id) {
            return base.Channel.ObtenerAsync(id);
        }
        
        public string Ingresar(Pacifico.SINCO.EN.SiniestroEN siniestro) {
            return base.Channel.Ingresar(siniestro);
        }
        
        public System.Threading.Tasks.Task<string> IngresarAsync(Pacifico.SINCO.EN.SiniestroEN siniestro) {
            return base.Channel.IngresarAsync(siniestro);
        }
        
        public string Actualizar(Pacifico.SINCO.EN.SiniestroEN siniestro) {
            return base.Channel.Actualizar(siniestro);
        }
        
        public System.Threading.Tasks.Task<string> ActualizarAsync(Pacifico.SINCO.EN.SiniestroEN siniestro) {
            return base.Channel.ActualizarAsync(siniestro);
        }
        
        public string RegistrarProceso(int id) {
            return base.Channel.RegistrarProceso(id);
        }
        
        public System.Threading.Tasks.Task<string> RegistrarProcesoAsync(int id) {
            return base.Channel.RegistrarProcesoAsync(id);
        }
        
        public string RegistrarPendiente(int id) {
            return base.Channel.RegistrarPendiente(id);
        }
        
        public System.Threading.Tasks.Task<string> RegistrarPendienteAsync(int id) {
            return base.Channel.RegistrarPendienteAsync(id);
        }
        
        public string Consultar(string numSiniestro, string tipo) {
            return base.Channel.Consultar(numSiniestro, tipo);
        }
        
        public System.Threading.Tasks.Task<string> ConsultarAsync(string numSiniestro, string tipo) {
            return base.Channel.ConsultarAsync(numSiniestro, tipo);
        }
        
        public string Aperturar(Pacifico.SINCO.EN.SiniestroEN siniestro) {
            return base.Channel.Aperturar(siniestro);
        }
        
        public System.Threading.Tasks.Task<string> AperturarAsync(Pacifico.SINCO.EN.SiniestroEN siniestro) {
            return base.Channel.AperturarAsync(siniestro);
        }
        
        public string RegistrarAsistido(int id) {
            return base.Channel.RegistrarAsistido(id);
        }
        
        public System.Threading.Tasks.Task<string> RegistrarAsistidoAsync(int id) {
            return base.Channel.RegistrarAsistidoAsync(id);
        }
        
        public string RegistrarAprobado(int id) {
            return base.Channel.RegistrarAprobado(id);
        }
        
        public System.Threading.Tasks.Task<string> RegistrarAprobadoAsync(int id) {
            return base.Channel.RegistrarAprobadoAsync(id);
        }
    }
}
