//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.SINCO.WEB.wsOrden {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsOrden.IOrdenWS")]
    public interface IOrdenWS {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenWS/ObtenerNombreWS", ReplyAction="http://tempuri.org/IOrdenWS/ObtenerNombreWSResponse")]
        string ObtenerNombreWS();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenWS/ObtenerNombreWS", ReplyAction="http://tempuri.org/IOrdenWS/ObtenerNombreWSResponse")]
        System.Threading.Tasks.Task<string> ObtenerNombreWSAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenWS/Agregar", ReplyAction="http://tempuri.org/IOrdenWS/AgregarResponse")]
        string Agregar(Pacifico.SINCO.EN.OrdenEN model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenWS/Agregar", ReplyAction="http://tempuri.org/IOrdenWS/AgregarResponse")]
        System.Threading.Tasks.Task<string> AgregarAsync(Pacifico.SINCO.EN.OrdenEN model);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrdenWSChannel : Pacifico.SINCO.WEB.wsOrden.IOrdenWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrdenWSClient : System.ServiceModel.ClientBase<Pacifico.SINCO.WEB.wsOrden.IOrdenWS>, Pacifico.SINCO.WEB.wsOrden.IOrdenWS {
        
        public OrdenWSClient() {
        }
        
        public OrdenWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrdenWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdenWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdenWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ObtenerNombreWS() {
            return base.Channel.ObtenerNombreWS();
        }
        
        public System.Threading.Tasks.Task<string> ObtenerNombreWSAsync() {
            return base.Channel.ObtenerNombreWSAsync();
        }
        
        public string Agregar(Pacifico.SINCO.EN.OrdenEN model) {
            return base.Channel.Agregar(model);
        }
        
        public System.Threading.Tasks.Task<string> AgregarAsync(Pacifico.SINCO.EN.OrdenEN model) {
            return base.Channel.AgregarAsync(model);
        }
    }
}
